#!/usr/bin/env bash

if [[ -d "./devScripts" ]]; then

    mkdir -p ./.vscode

    echo "Creating VSCode launch.json file"
    echo '{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Web Server",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "args": [
                "${workspaceFolder}/devScripts/webserver.js",
                "-p",
                "8080",
                "-d",
                "${workspaceFolder}/src",
                "--enable_cors",
                "--verbose"
            ],
        }
    ]
}' > ./.vscode/launch.json

    echo "Creating VSCode snippets file"
    echo '{
	"Main Stub for BitBurner scripts": {
		"scope": "javascript,typescript",
		"prefix": "nsmain",
		"body": [
			"$BLOCK_COMMENT_START TODO: Update what this scripts intention is",
			" $BLOCK_COMMENT_END",
			"",
			"$BLOCK_COMMENT_START*",
			" * @param {import(\".\").NS} ns Use just \"@param {NS} ns\" if editing in game",
			" $BLOCK_COMMENT_END",
			"export async function main(ns) {",
			"}",
			"",
		],
		"description": "Creates the shell of a BitBurner script"
	}
}' > ./.vscode/main.code-snippets

    echo "Setup VSCode script complete!"

else
    echo "This script is designed to be run from the root of the project. Please change directory back to this location and run the script again."
fi