#!/usr/bin/env bash

if [[ -d "./devScripts" ]]; then

    echo "Creating VSCode launch.json file"
    mkdir -p ./.vscode
    echo '{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Web Server",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "args": [
                "${workspaceFolder}/devScripts/webserver.js",
                "-p",
                "8080",
                "-d",
                "${workspaceFolder}",
                "--enable_cors",
                "--verbose"
            ],
        }
    ]
}' > ./.vscode/launch.json

    echo "Setup VSCode script complete!"

else
    echo "This script is designed to be run from the root of the project. Please change directory back to this location and run the script again."
fi