#! /usr/bin/env bash

echo "Fetching updated types script from bitburner official repository."
rm -f ./index.d.ts
curl -L https://raw.githubusercontent.com/danielyxie/bitburner/dev/src/ScriptEditor/NetscriptDefinitions.d.ts -o ./src/index.d.ts
echo "updateTypes script has completed"